MVC_dbt_local:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: pgdatabase
      port: 5432
      user: root
      pass: root
      dbname: MVC_db
      schema: public
  target: dev